name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Workflow Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          reaction-token: ${{ secrets.PAT }}
          commands: |
            desktop
